"""fix table columns testruns, testresults

Revision ID: 6f80d45e90a6
Revises: b2b16619bada
Create Date: 2026-04-03 23:05:47.177936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f80d45e90a6'
down_revision: Union[str, Sequence[str], None] = 'b2b16619bada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testresults', sa.Column('testrun_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'testresults', 'testruns', ['testrun_id'], ['id'])
    op.add_column('testruns', sa.Column('title', sa.String(), nullable=False))
    op.add_column('testruns', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('testruns', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('testruns', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('testruns', sa.Column('status', sa.String(), nullable=False))
    op.add_column('testruns', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'testruns', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testruns', type_='foreignkey')
    op.drop_column('testruns', 'description')
    op.drop_column('testruns', 'status')
    op.drop_column('testruns', 'completed_at')
    op.drop_column('testruns', 'started_at')
    op.drop_column('testruns', 'owner_id')
    op.drop_column('testruns', 'title')
    op.drop_constraint(None, 'testresults', type_='foreignkey')
    op.drop_column('testresults', 'testrun_id')
    # ### end Alembic commands ###
